//Below code is generated by GitHub Copilot and modified by me to fit my project requirements.
// `src/main/java/com/example/liambuckleyfyp/controller/GolfCourseController.java`
// `src/main/java/com/example/liambuckleyfyp/controller/GolfCourseController.java`
package com.example.liambuckleyfyp.controller;

import jakarta.persistence.MapKeyColumn;
import jakarta.servlet.http.HttpSession;
import com.example.liambuckleyfyp.model.GolfCourse;
import com.example.liambuckleyfyp.service.GolfCourseService;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class GolfCourseController {

    // Creates a logger instance for the GolfCourseController class
    private static final Logger logger = LoggerFactory.getLogger(GolfCourseController.class.getName());

    @Autowired
    private GolfCourseService golfCourseService;

    // Handles GET requests to "/golfcourses" and returns a list of all golf courses
    @GetMapping("/golfcourses")
    public String getAllGolfCourses(Model model, HttpSession session) {
        List<GolfCourse> golfCourses = golfCourseService.getAllGolfCourses();
        model.addAttribute("golfCourses", golfCourses);
        String userLogin = (String) session.getAttribute("userLogin");
        model.addAttribute("userLogin", userLogin);
        return "golfcourse_list";
    }

    // Handles GET requests to "/golfcourse/{id}" and returns details of a specific golf course
    @GetMapping("/golfcourse/{id}")
    public String getGolfCourseDetails(@PathVariable("id") int id, Model model) {
        GolfCourse golfCourse = golfCourseService.getGolfCourseById(id);
        model.addAttribute("golfCourse", golfCourse);
        // Log the times map
        logger.info("GolfCourse times: " + golfCourse.getTimes());
        return "individualgolfcourse";
    }

    // Handles POST requests to "/book" and processes a booking for a specific time slot
    @PostMapping("/book")
    public String bookTime(@RequestParam("golfCourseId") Long golfCourseId, @RequestParam("time") String time, @RequestParam("date") String date, Model model, HttpSession session) {
        // Fetch the golf course details using the golfCourseId
        GolfCourse golfCourse = golfCourseService.getGolfCourseById(golfCourseId.intValue());

        // Add the golf course, time, and date to the model
        model.addAttribute("golfCourse", golfCourse);
        model.addAttribute("time", time);
        model.addAttribute("date", date);

        // Get the logged-in user's name from the session and add it to the model
        String userLogin = (String) session.getAttribute("userLogin");
        model.addAttribute("userLogin", userLogin);

        // Redirect to the booking confirmation page
        return "booking_confirmation";
    }
}
//References
//GitHub Co-pilot
//License to: Liam Buckley(liambuckley02)
//License restriction: For educational use only
//Valid through: November 2nd 2025